version: '3.10'

services:
  redis:
    image: redis:alpine
    networks:
      - backend

  db:
    image: postgres:alpine
    networks:
      - backend

  vote:
    image: dockersamples/examplevotingapp_vote:latest
    ports:
      - 5000:80
    links:
      - redis
    networks:
      - frontend
      - backend

  result:
    image: dockersamples/examplevotingapp_result
    ports:
      - 5001:80
    links:
      - db
    networks:
      - frontend
      - backend

  worker:
    image: dockersamples/examplevotingapp_worker
    links:
      - redis
      - db
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend: